### ISSUE TITLE
Arayüz olmasına gerek yok ama bir fonksiyonda en son çalıştırılma zamanı bilgisi yer alması

### ISSUE THREAD

**Issue by aliorhun** [furkansandal/Stig4PardusGUI#10]
Arayüz olmasına gerek yok ama bir fonksiyonda en son çalıştırılma zamanı bilgisi yer alması. Ve daha önce çalıştırılan verilerin dosya veya küçük bir db'de (örneğin sqlite) bulunması.

**Comment by furkansandal** [comment]
veritabanını oluşturdum. Verileri tek tek txt dosyasından parse etmek çok zahmetli olduğundan veriler.db dosyasında kurallar tablosuna ekledim. Sıradaki adımda logları veritabanına kayıt edip daha sonraki seviyede html-pdf çıktı seçeneği sunup local kayıt yada mail post eklemeyi düşünüyorum.

**Comment by aliorhun** [comment]
Uygundur, oldukça güzel olur.

**Comment by furkansandal** [comment]
Tamamlandı sqlite, html ve json çıktıları artık mevcut.
