### ISSUE TITLE
"Kaldı" formatında olan maddelerin madde numaralarının json verisi olarak döndürülmesi

### ISSUE THREAD

**Issue by aliorhun** [furkansandal/Stig4PardusGUI#9]
"Kaldı" formatında olan maddelerin madde numaralarının json verisi olarak döndürülmesi sağlanabilir. Böylelikle ileride yine çalıştırıldığında hangi maddelerde hata vardı ve çözüldü; veya yeni hatalar var mı diye.

**Comment by furkansandal** [comment]
.json uzantılı json formatında çıktı vereceğim. son ve tümü olarak.

**Comment by aliorhun** [comment]
Aynen oldukça güzel olur. kaldı verilerini okuyabilmek için.

**Comment by furkansandal** [comment]
Tamamlandı
